stages:
  - test

basic_check:
  stage: test
  image: python:3.9
  script:

    - echo "Running basic Django check..."
    - pip install -r requirements.txt
    - cd RepairCafe  
    - python manage.py check --deploy
  allow_failure: true  