basic_check:
  stage: test
  image: python:3.9
  script:
    - echo "Running basic Django check..."
    - pip install -r requirements.txt
    - cd RepairCafe
    - python manage.py check --deploy
  allow_failure: false

run_tests:
  stage: test
  image: python:3.9
  script:
    - echo "Running unit tests..."
    - pip install -r requirements.txt
    - cd RepairCafe
    - pytest
  allow_failure: false
