default:
  image: python:3.9

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Installing dependencies..."
    - python -m venv venv
    - venv/bin/pip install -r requirements.txt
  artifacts:
    paths:
      - venv/

basic_check:
  stage: test 
  script:
    - echo "Running basic Django check..."
    - cd RepairCafe
    - ../venv/bin/python manage.py check --deploy
  allow_failure: true
  dependencies:
    - build 


flake8_lint:
  stage: test
  script:
    - echo "Running Flake8..."
    - cd RepairCafe
    - ../venv/bin/flake8 --format=pylint > flake8_report.txt || true
  artifacts:
    paths:
      - RepairCafe/flake8_report.txt
  allow_failure: true
  dependencies:
    - build 

run_tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - cd RepairCafe
    - ../venv/bin/pytest
  allow_failure: true
  dependencies:
    - build 

deploy:
  stage: deploy
  script:
    - cd RepairCafe
    - echo "Skipping deployment for now..."
  only:
    - main  
  dependencies:
    - build 
